#first step of dockerizing, we should create a couple of files here. They are Dockerfile, docker-compose.yml , and .dockerignore files. Dockerfile is to run node and mongo in two different containers. And the docker-compose file is to in here we need to run both node and Mongo containers at the same time.

# version: '3.9'

# services:
#   # Mongo services
#   mongo_db:
#     container_name: ecom_container
#     image: mongo:latest
#     restart: always
#     volumes:
#       - mongo_data:/data/db

#   # Node api services
#   api:
#     build: .
#     ports:
#       - 4000:3002
#     environment:
#       PORT: 3002
#       MONGODB_URI: mongodb://127.0.0.1:27017
#       DB_NAME: ecom-stripe
#     depends_on:
#       - mongo_db

# volumes:
#   mongo_data: {}



version: '3.8'
services:
  mongo:
    image: mongo:6.0.13
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-config:/data
      - mongo-data:/data/db
  node:
    image: node:20.11.0-alpine
    user: ${NODE_USER}
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
    command: "yarn start"
    ports:
      - 3002:${NODE_PORT}
    volumes:
      - ./:/home/node/app
    depends_on:
      - mongo
volumes:
  mongo-config:
  mongo-data: