#first step of dockerizing, we should create a couple of files here. They are Dockerfile, docker-compose.yml , and .dockerignore files. Dockerfile is to run node and mongo in two different containers. And the docker-compose file is to in here we need to run both node and Mongo containers at the same time.

version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - .data:/data/db
